services:
  back:
    build:
      context: ./back
    ports:
      - "4000:4000"
    volumes:
      - ./back:/app
      - /app/node_modules
    environment:
      PORT: 4000
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - db
      - redis

  front:
    build:
      context: ./front
      args:
        PORT: 3009
    volumes:
      - ./front:/app
      - /app/node_modules
    ports:
      - "3009:3009"
    environment:
      - PORT=3009
      - REACT_APP_API_URL=http://localhost:4000

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: canary
      POSTGRES_PASSWORD: canary
      POSTGRES_DB: db
    ports:
      - "7432:5432"
    volumes:
      - ./tmp/db:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

volumes:
  redis_data:
